replicaCount: 1

image:
  repository: ghcr.io/opentelekomcloud/t-cloud-public-rancher-network-controller
  tag: "0.1.0"
  pullPolicy: IfNotPresent

leaderElection: true

resources:
  requests:
    cpu: 10m
    memory: 64Mi
  limits:
    cpu: 500m
    memory: 256Mi

podSecurityContext:
  runAsNonRoot: true

securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop: [ALL]

