apiVersion: apps/v1
kind: Deployment
metadata:
  name: t-cloud-network-controller
  namespace: cattle-tcloud-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: t-cloud-network-controller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: t-cloud-network-controller
    spec:
      serviceAccountName: t-cloud-network-controller
      securityContext:
        runAsNonRoot: true
      containers:
        - name: manager
          image: ghcr.io/opentelekomcloud/t-cloud-public-rancher-network-controller:dev
          args:
            - --leader-elect
          ports:
            - name: metrics
              containerPort: 8080
            - name: health
              containerPort: 8081
          livenessProbe:
            httpGet:
              path: /healthz
              port: health
          readinessProbe:
            httpGet:
              path: /readyz
              port: health
          resources:
            requests:
              cpu: 10m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 256Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ALL]
            readOnlyRootFilesystem: true

